services:
  backend:
    build: ./backend
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_MODULE_LOADING=LAZY
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - whisper-models:/app/models
    command: uvicorn main:app --host ${API_HOST:-0.0.0.0} --port ${API_PORT:-8000} --reload
    networks:
      - whisper-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - whisper-network

networks:
  whisper-network:
    driver: bridge

volumes:
  whisper-models:
